services:
  - type: web
    name: zenvault
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node ./server/index.mjs
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_TOKEN_TTL
        value: 12h
      - key: PENDING_TOKEN_TTL
        value: 10m
