import { randomBytes } from 'crypto';

const insecureJwtSecrets = new Set([
  '',
  'change-this-secret',
  'qfs-wallet-dev-secret',
  'replace-with-your-own-64-character-random-secret',
  'replace-me',
  'dev-secret',
  'secret',
]);

const toTrimmedString = (value, fallback = '') => String(value ?? fallback).trim();

const parsePort = (value, fallback) => {
  const parsed = Number(value ?? fallback);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
};

let _autoGeneratedSecret = null;

const getAutoGeneratedSecret = () => {
  if (!_autoGeneratedSecret) {
    _autoGeneratedSecret = randomBytes(48).toString('hex');
    console.warn('[config] WARNING: JWT_SECRET is not set. A temporary secret has been generated automatically.');
    console.warn('[config] WARNING: All sessions will be invalidated on every server restart.');
    console.warn('[config] ACTION:  Set JWT_SECRET in your Render environment variables to fix this.');
  }
  return _autoGeneratedSecret;
};

export const buildConfig = (env = process.env) => {
  const nodeEnv = toTrimmedString(env.NODE_ENV, 'development') || 'development';
  const isProduction = nodeEnv === 'production';
  const isRender = Boolean(env.RENDER);
  let jwtSecret = toTrimmedString(env.JWT_SECRET);

  if (!jwtSecret || jwtSecret.length < 32 || insecureJwtSecrets.has(jwtSecret)) {
    jwtSecret = getAutoGeneratedSecret();
  }

  const clientOrigin = toTrimmedString(env.CLIENT_ORIGIN, isProduction ? '' : 'http://localhost:5173');

  return {
    nodeEnv,
    isProduction,
    isRender,
    apiPort: parsePort(env.PORT ?? env.API_PORT, 4000),
    sqliteDbPath: toTrimmedString(env.SQLITE_DB_PATH, '') || null,
    jwtSecret,
    clientOrigin,
    accessTokenTtl: toTrimmedString(env.ACCESS_TOKEN_TTL, '12h') || '12h',
    pendingTokenTtl: toTrimmedString(env.PENDING_TOKEN_TTL, '10m') || '10m',
  };
};
